// Physical display units currently on the showroom floor, distinct from the
// online product catalogs — used so the chat bot can answer "what's on
// display at the X showroom" without inventing units that aren't there.
// Sourced from showroom inventory lists provided by the business owner.
// `name` is the real marketing name when the site has a matching catalog
// product; otherwise it's brand + manufacturer SKU (never a fabricated name).
export type ShowroomUnit = {
  name: string;
  brand: string;
  pairedMantel?: string;
};

export const showroomInventory: { city: string; units: ShowroomUnit[] }[] = [
  {
    city: "Sacramento",
    units: [
      { name: "Cortlin Linear Fire Pit Bowl (Corten-steel look, 100,000 BTU)", brand: "The Outdoor GreatRoom Company" },
      { name: "Cove Edge Round Gas Fire Pit Bowl (42\", White)", brand: "The Outdoor GreatRoom Company (sold by Calmantel)" },
      { name: "Dimplex BFSL33 Electric Fireplace", brand: "Dimplex" },
      { name: "Dimplex BLF5051 Electric Fireplace", brand: "Dimplex" },
      { name: "Dimplex XLF100 Electric Fireplace", brand: "Dimplex" },
      { name: "Dimplex XLF6017-XD Electric Fireplace", brand: "Dimplex" },
      { name: "Empire DVCT40CBP95N Gas Fireplace", brand: "Empire", pairedMantel: "Turin Mantel" },
      { name: "Empire DVLL60BP90N Gas Fireplace", brand: "Empire", pairedMantel: "Darlinghurst Beam" },
      { name: "Empire Plaza Gas Fireplace", brand: "Empire" },
      { name: "Fire Table", brand: "Calmantel (FBL-06LP)" },
      { name: "Flare Outdoor Linear Gas Fireplace (70\")", brand: "Flare" },
      { name: "Heat & Glo 6K Series Gas Fireplace", brand: "Heat & Glo", pairedMantel: "Pitcairn Mantel" },
      { name: "Heat & Glo 8K Series Gas Fireplace", brand: "Heat & Glo", pairedMantel: "Dominique Mantel (Oyster White / Parchment finish)" },
      { name: "Heat & Glo Cosmo 42 Gas Fireplace Insert", brand: "Heat & Glo" },
      { name: "Heat & Glo Cosmo Gas Fireplace Insert (35\")", brand: "Heat & Glo" },
      { name: "Heatilator DV4236 Gas Fireplace", brand: "Heatilator", pairedMantel: "Ceduna Mantel" },
      { name: "Heat & Glo Escape Gas Fireplace Insert (42\")", brand: "Heat & Glo", pairedMantel: "Padthaway Mantel" },
      { name: "Heat & Glo Escape Gas Fireplace Insert (35\")", brand: "Heat & Glo" },
      { name: "Stellar Foundation 4' Pier Fire Feature", brand: "Stellar (HHT)" },
      { name: "Stellar Foundation 5' Single-Sided Fire Feature", brand: "Stellar (HHT)" },
      { name: "Heat & Glo Mezzo Linear Gas Fireplace (60\")", brand: "Heat & Glo" },
      { name: "Heatilator NDV4236 Gas Fireplace", brand: "Heatilator", pairedMantel: "Barossa Mantel" },
      { name: "Courtyard Outdoor Gas Fireplace (42\")", brand: "Heat & Glo" },
      { name: "Outdoor Fortress Gas Fireplace (36\")", brand: "Heat & Glo" },
      { name: "Lanai Outdoor Fireplace (51\")", brand: "Heat & Glo", pairedMantel: "Hackney Beam" },
      { name: "Heat & Glo Paloma Modern Gas Fireplace", brand: "Heat & Glo" },
      { name: "Heat & Glo Primo II Linear Fireplace (60\")", brand: "Heat & Glo" },
      { name: "Heat & Glo Provident Gas Fireplace Insert (30\")", brand: "Heat & Glo" },
      { name: "SimpliFire Built-In 36 Electric Fireplace", brand: "SimpliFire", pairedMantel: "Benedict Mantel" },
      { name: "SimpliFire Insert 35 Electric Fireplace", brand: "SimpliFire" },
      { name: "SimpliFire Scion 55 Electric Fireplace", brand: "SimpliFire" },
      { name: "Heat & Glo SlimLine 7 Gas Fireplace", brand: "Heat & Glo", pairedMantel: "Gosford Mantel" },
      { name: "Heat & Glo SlimLine 9X Gas Fireplace", brand: "Heat & Glo", pairedMantel: "Cannes Mantel" },
      { name: "Heat & Glo Supreme Gas Fireplace Insert (30\")", brand: "Heat & Glo" },
      { name: "Heat & Glo Supreme Gas Fireplace Insert (30\", Birch log set)", brand: "Heat & Glo" },
      { name: "Heat & Glo Supreme Gas Fireplace Insert (35\")", brand: "Heat & Glo" },
      { name: "Heat & Glo True Gas Fireplace (36\")", brand: "Heat & Glo", pairedMantel: "Versailles Mantel" },
      { name: "Heat & Glo True Gas Fireplace Insert (50\")", brand: "Heat & Glo" },
      { name: "Superior DRT3535DEN-B Gas Fireplace", brand: "Superior (IHP)", pairedMantel: "Tonso Mantel" },
      { name: "Superior VRE4542 Gas Fireplace", brand: "Superior (IHP)" },
      { name: "Magra Hearth Fire Feature", brand: "Magra" },
      { name: "Magra Hearth Fire Feature", brand: "Magra" },
      { name: "Modern Flames Landscape FullView (80\")", brand: "Modern Flames" },
      { name: "Modern Flames Orion Slim 52\"", brand: "Modern Flames" },
      { name: "Modern Flames Redstone Electric Fireplace Insert (42\")", brand: "Modern Flames" },
      { name: "Napoleon Altitude X 42 Gas Fireplace", brand: "Napoleon", pairedMantel: "Bolte Mantel" },
      { name: "Napoleon Ascent 36 Gas Fireplace", brand: "Napoleon", pairedMantel: "Manly Mantel" },
      { name: "Napoleon Elevation X 42 Gas Fireplace", brand: "Napoleon", pairedMantel: "Torrens Mantel" },
      { name: "Napoleon Oakville Gas Fireplace Insert", brand: "Napoleon" },
      { name: "Napoleon StarFire Gas Fireplace", brand: "Napoleon", pairedMantel: "Bondi Mantel" },
      { name: "Napoleon Vector 50 Gas Fireplace", brand: "Napoleon", pairedMantel: "Wood Beam" },
      { name: "Napoleon Luxuria 74 Gas Fireplace", brand: "Napoleon", pairedMantel: "Hollywood Park Beam" },
      { name: "Napoleon NEF124H Electric Fireplace", brand: "Napoleon" },
      { name: "Napoleon NEF332-5019W Electric Fireplace", brand: "Napoleon" },
      { name: "Napoleon NEFB50H-3SV Electric Fireplace", brand: "Napoleon" },
      { name: "Napoleon Allure 42 Electric Fireplace", brand: "Napoleon" },
      { name: "Napoleon NEFL60CHS Electric Fireplace", brand: "Napoleon" },
      { name: "Napoleon NEFL72CFH Electric Fireplace", brand: "Napoleon" },
      { name: "Napoleon NEFL74CHD-1 Electric Fireplace", brand: "Napoleon" },
      { name: "Napoleon NEFP32-5019W Electric Fireplace", brand: "Napoleon" },
      { name: "NetZero E1 Fire Feature", brand: "NetZero Fire" },
      { name: "NetZero NZ60B Fire Feature", brand: "NetZero Fire" },
      { name: "NetZero WaterPlace Fire & Water Feature", brand: "NetZero Fire" },
      { name: "Ortal Insert 34 Gas Fireplace", brand: "Ortal" },
      { name: "Ortal Wilderness Traditional 42 Gas Fireplace", brand: "Ortal" },
      { name: "Osburn OB00950 Wood-Burning Insert", brand: "Osburn" },
      { name: "Stellar 6' 4-Sided 30\" High Glass Fire Feature", brand: "Stellar" },
      { name: "Versailles Mantel", brand: "Calmantel" },
    ],
  },
  {
    city: "Dublin",
    units: [
      { name: "Dimplex BLF5051 Electric Fireplace", brand: "Dimplex" },
      { name: "Dimplex GBF1500-Pro Electric Fireplace", brand: "Dimplex" },
      { name: "Dimplex RBF42WC Electric Fireplace", brand: "Dimplex" },
      { name: "Dimplex XLF7417-XD Electric Fireplace", brand: "Dimplex" },
      { name: "Dimplex XLF-F7417-XD Electric Fireplace", brand: "Dimplex" },
      { name: "Dimplex Opti-V Duet Electric Fireplace (54\", VF5452L)", brand: "Dimplex" },
      { name: "Empire DVCT40CFP95 Gas Fireplace", brand: "Empire", pairedMantel: "Bolte Mantel (Traditional, Monaco finish)" },
      { name: "Empire DVLL60BP90N Gas Fireplace", brand: "Empire", pairedMantel: "Hollywood Park Beam" },
      { name: "Empire Plaza Gas Fireplace", brand: "Empire" },
      { name: "Flare Outdoor Linear Gas Fireplace (70\")", brand: "Flare (FLARE-LC-70-H)" },
      { name: "Heat & Glo 6K Series Gas Fireplace", brand: "Heat & Glo", pairedMantel: "Manly Mantel (Portland Gray finish)" },
      { name: "Heat & Glo 8KX Series Gas Fireplace", brand: "Heat & Glo", pairedMantel: "Dominique Mantel" },
      { name: "Heat & Glo Cosmo 42 Gas Fireplace Insert", brand: "Heat & Glo", pairedMantel: "Oodlawera Beam" },
      { name: "Heat & Glo Cosmo Gas Fireplace Insert (35\")", brand: "Heat & Glo" },
      { name: "Heat & Glo Escape Gas Fireplace Insert (35\")", brand: "Heat & Glo" },
      { name: "Heat & Glo Mezzo Linear Gas Fireplace (60\")", brand: "Heat & Glo", pairedMantel: "Hackney Beam (Southwest London finish)" },
      { name: "Heatilator NDV4236I-B Gas Fireplace", brand: "Heatilator", pairedMantel: "Barossa Mantel (Portland Gray finish)" },
      { name: "Courtyard Outdoor Gas Fireplace (42\", Pier Housing)", brand: "Heat & Glo", pairedMantel: "Nullarbor Mantel (Small Monaco finish)" },
      { name: "Outdoor Fortress Gas Fireplace (36\")", brand: "Heat & Glo", pairedMantel: "Yarra Mantel (Southwest finish)" },
      { name: "Lanai Outdoor Fireplace (51\")", brand: "Heat & Glo", pairedMantel: "Darlinghurst Beam (Traditional, Monaco finish)" },
      { name: "Heat & Glo Primo II Linear Fireplace (60\")", brand: "Heat & Glo" },
      { name: "Heat & Glo Provident Gas Fireplace Insert (35\")", brand: "Heat & Glo" },
      { name: "SimpliFire Insert 35 Electric Fireplace", brand: "SimpliFire" },
      { name: "Heat & Glo SlimLine 7 Gas Fireplace", brand: "Heat & Glo", pairedMantel: "Gosford Mantel (Traveled Kings finish)" },
      { name: "Heat & Glo SlimLine 9X Gas Fireplace", brand: "Heat & Glo", pairedMantel: "Torrens Mantel (Oyster White, Aspen finish)" },
      { name: "Heat & Glo Supreme Gas Fireplace Insert (30\", Birch log set)", brand: "Heat & Glo" },
      { name: "Heat & Glo Supreme Gas Fireplace Insert (35\")", brand: "Heat & Glo" },
      { name: "Heat & Glo True Gas Fireplace (42\", Tall Glass)", brand: "Heat & Glo", pairedMantel: "Bondi Mantel (Smoke finish)" },
      { name: "Isokern Masonry Fireplace System (82048)", brand: "Isokern" },
      { name: "Modern Flames Redstone Electric Fireplace Insert (42\")", brand: "Modern Flames" },
      { name: "Napoleon AX42NTE Gas Fireplace", brand: "Napoleon", pairedMantel: "Tonso Mantel (Small Sea finish)" },
      { name: "Napoleon EX42NTEL Gas Fireplace", brand: "Napoleon", pairedMantel: "Sausalito Mantel (Small Sea finish)" },
      { name: "Napoleon LV50N Gas Fireplace", brand: "Napoleon", pairedMantel: "Darlinghurst Beam (Oyster White, London Fog finish)" },
      { name: "Napoleon LVX50NX Gas Fireplace", brand: "Napoleon", pairedMantel: "Darlinghurst Beam (Southwest, Grecian finish)" },
      { name: "Napoleon NEFB50H-3SV Electric Fireplace", brand: "Napoleon" },
      { name: "Napoleon NEFL50CHS Electric Fireplace", brand: "Napoleon" },
      { name: "Napoleon NEFL50FH-MT Electric Fireplace", brand: "Napoleon" },
      { name: "Napoleon NEFL50H-3SV Electric Fireplace", brand: "Napoleon" },
      { name: "Napoleon NEFL60CHS Electric Fireplace", brand: "Napoleon" },
      { name: "Napoleon XLF50 Electric Fireplace", brand: "Napoleon" },
      { name: "NetZero E1 100 Fire Feature", brand: "NetZero Fire" },
      { name: "NetZero Water NZWP40B Fire & Water Feature", brand: "NetZero Fire" },
      { name: "Cortlin Linear Fire Pit Bowl (Corten-steel look, 100,000 BTU)", brand: "The Outdoor GreatRoom Company" },
      { name: "Ortal Electra 60 Electric Fireplace", brand: "Ortal" },
      { name: "Ortal Wilderness Traditional 42 Gas Fireplace", brand: "Ortal", pairedMantel: "Turin Mantel (Southwest London finish)" },
      { name: "Stellar 6' Single-Sided 2-Sided Glass Masonry Fire Feature", brand: "Stellar" },
      { name: "Stellar Foundation 5' Pier Fire Feature", brand: "Stellar" },
    ],
  },
  {
    city: "Anaheim",
    units: [
      { name: "Dimplex CDFI1000P Electric Fireplace Insert", brand: "Dimplex" },
      { name: "Dimplex XLF10017XD Electric Fireplace", brand: "Dimplex" },
      { name: "Dimplex XLF74 Electric Fireplace", brand: "Dimplex" },
      { name: "Empire DVCT40CBP95N Gas Fireplace", brand: "Empire" },
      { name: "Flare FF-45 Fire Feature", brand: "Flare" },
      { name: "Flare Outdoor Gas Fireplace", brand: "Flare" },
      { name: "Flare RC/LC-70 Outdoor Linear Gas Fireplace (70\")", brand: "Flare" },
      { name: "Heat & Glo 6KL Series Gas Fireplace", brand: "Heat & Glo" },
      { name: "Heat & Glo 8KX Series Gas Fireplace", brand: "Heat & Glo" },
      { name: "Heat & Glo Cosmo 42 Gas Fireplace Insert", brand: "Heat & Glo" },
      { name: "Heat & Glo Cosmo Gas Fireplace Insert (30\")", brand: "Heat & Glo" },
      { name: "Heat & Glo Cosmo Gas Fireplace Insert (35\")", brand: "Heat & Glo" },
      { name: "Heat & Glo Escape Gas Fireplace Insert (42\")", brand: "Heat & Glo" },
      { name: "Heat & Glo Escape Gas Fireplace Insert (35\")", brand: "Heat & Glo" },
      { name: "Stellar Foundation 4' Pier Fire Feature", brand: "Stellar (HHT)" },
      { name: "Stellar Foundation 5' Single-Sided Fire Feature", brand: "Stellar (HHT)" },
      { name: "Heat & Glo Mezzo Linear Gas Fireplace (48\")", brand: "Heat & Glo" },
      { name: "Heat & Glo Mezzo Linear Gas Fireplace (60\")", brand: "Heat & Glo" },
      { name: "Courtyard Outdoor Gas Fireplace (36\", Pier Housing)", brand: "Heat & Glo" },
      { name: "Lanai Outdoor Fireplace (51\")", brand: "Heat & Glo" },
      { name: "Lanai Outdoor Fireplace (60\")", brand: "Heat & Glo" },
      { name: "Heat & Glo Primo II Linear Fireplace (60\")", brand: "Heat & Glo" },
      { name: "Heat & Glo Provident Gas Fireplace Insert (35\")", brand: "Heat & Glo" },
      { name: "SimpliFire Built-In 36 Electric Fireplace", brand: "SimpliFire" },
      { name: "SimpliFire Format 36 Electric Fireplace", brand: "SimpliFire" },
      { name: "SimpliFire Inception 36 Electric Fireplace", brand: "SimpliFire" },
      { name: "SimpliFire Insert 35 Electric Fireplace", brand: "SimpliFire" },
      { name: "SimpliFire Scion 78 Electric Fireplace (Black)", brand: "SimpliFire" },
      { name: "SimpliFire Scion Trim 43 Electric Fireplace (Black)", brand: "SimpliFire" },
      { name: "SimpliFire Trend 78 Electric Fireplace", brand: "SimpliFire" },
      { name: "Heat & Glo SlimLine 7X Gas Fireplace", brand: "Heat & Glo" },
      { name: "Heat & Glo Supreme Gas Fireplace Insert (30\")", brand: "Heat & Glo" },
      { name: "Heat & Glo Supreme Gas Fireplace Insert (30\", Birch log set)", brand: "Heat & Glo" },
      { name: "Heat & Glo Supreme Gas Fireplace Insert (35\")", brand: "Heat & Glo" },
      { name: "Heat & Glo True Gas Fireplace (42\", Tall Glass)", brand: "Heat & Glo" },
      { name: "Superior DRT6345TEN Gas Fireplace", brand: "Superior (IHP)" },
      { name: "Modern Flames Orion Slim 52\"", brand: "Modern Flames" },
      { name: "Modern Flames Redstone Electric Fireplace Insert (42\")", brand: "Modern Flames" },
      { name: "Napoleon Trivista 3-Sided Gas Fireplace", brand: "Napoleon" },
      { name: "Napoleon AX42NTE Gas Fireplace", brand: "Napoleon" },
      { name: "Napoleon EX36NTEL Gas Fireplace", brand: "Napoleon" },
      { name: "Napoleon LV50N-2 Gas Fireplace", brand: "Napoleon" },
      { name: "Napoleon LVX74NX Gas Fireplace", brand: "Napoleon" },
      { name: "Napoleon NEFL65LCD-35V Electric Fireplace", brand: "Napoleon" },
      { name: "Napoleon Tall Linear Vector Gas Fireplace (74\")", brand: "Napoleon" },
      { name: "NetZero E1 Fire Feature", brand: "NetZero Fire" },
      { name: "Ortal WRT42DG Gas Fireplace", brand: "Ortal" },
      { name: "Ortal Electra 32 or 40 Electric Fireplace", brand: "Ortal" },
      { name: "Ortal FR60 Gas Fireplace", brand: "Ortal" },
      { name: "Ortal Holographic 60 Gas Fireplace", brand: "Ortal" },
      { name: "Ortal Wilderness Traditional 42 Gas Fireplace", brand: "Ortal" },
    ],
  },
];
